language: python

python:
  - "3.5"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install codecov

env:
  - DJANGO_SETTINGS_MODULE=hart.settings.travis

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - coverage run --source godpanel --source godpanel ./manage.py test

after_success:
  - codecov
