language: python

python:
  - "3.5"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install codecov

env:
  - DJANGO_SETTINGS_MODULE=hart.settings.travis

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - coverage run --source godpanel --source godpanel ./manage.py test

after_success:
  - codecov
  - curl --data "Travis CI build successful for Python ${TRAVIS_PYTHON_VERSION} on $(date) - (https://travis-ci.org/h-art/Godpanel/jobs/${TRAVIS_JOB_ID})" https://h-art.slack.com/services/hooks/slackbot\?token=${SLACK_TOKEN}\&channel=${SLACK_CHANNEL}

after_failure:
  - curl --data "Travis CI build failed for Python ${TRAVIS_PYTHON_VERSION} on $(date) - (https://travis-ci.org/h-art/Godpanel/jobs/${TRAVIS_JOB_ID})" https://h-art.slack.com/services/hooks/slackbot\?token=${SLACK_TOKEN}\&channel=${SLACK_CHANNEL}
