language: python

python:
  - "3.5"

install: "pip install -r requirements.txt"

env:
  - DJANGO_ENV=travis

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - coverage run --source godpanel --omit "godpanel/migrations/*.py" ./manage.py test
  - coverage xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
