# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 21, 18, 0)),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 21, 9, 0)),
        ),
    ]
