# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='end',
            field=models.DateTimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='start',
            field=models.DateTimeField(default=timezone.now()),
        ),
    ]
