# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20160421_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='saturation',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='start',
            field=models.DateField(default=datetime.datetime(2016, 4, 21, 18, 49, 16, 224549)),
        ),
    ]
