# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20160421_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='saturation',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='start',
            field=models.DateField(default=datetime.datetime(2016, 4, 21, 19, 0, 17, 176038)),
        ),
    ]
