# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20160421_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='allocation',
            name='allocation_type',
            field=models.CharField(choices=[('allocation', 'Allocation'), ('pre-allocation', 'Pre allocation'), ('guess', 'Guess')], default=('allocation', 'Allocation'), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='start',
            field=models.DateField(default=datetime.datetime(2016, 4, 21, 19, 16, 28, 40694)),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Client'),
        ),
    ]
