# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20160421_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='start',
            field=models.DateField(),
        ),
    ]
