# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20160421_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocation_type',
            field=models.CharField(choices=[('allocation', 'Allocation'), ('pre-allocation', 'Pre allocation'), ('guess', 'Guess')], default='allocation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='start',
            field=models.DateField(),
        ),
    ]
